=== Josecgh/festival-tech/festival.dtd
<!ELEMENT festival (nombre, ciudad, fechas, lugar, actividades, contacto, planes)>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT ciudad (#PCDATA)>
<!ELEMENT fechas (fecha*)>
<!ELEMENT fecha (dia, mes, num, anio)>
<!ELEMENT dia (#PCDATA)>
<!ELEMENT mes (#PCDATA)>
<!ELEMENT num (#PCDATA)>
<!ELEMENT anio (#PCDATA)>
<!ELEMENT lugar (#PCDATA)>
<!ELEMENT actividades (actividad*)>
<!ELEMENT actividad (titulo, descripcion, hora, precio)>
<!ATTLIST actividad id ID #REQUIRED tipo (robotica | videojuegos | ia | realidad_virtual | programacion | ciberseguridad) #REQUIRED>
<!ELEMENT titulo (#PCDATA)>
<!ELEMENT descripcion (#PCDATA)>
<!ELEMENT hora (#PCDATA)>
<!ELEMENT precio (#PCDATA)>
<!ELEMENT contacto (email?, telefono)>
<!ELEMENT email (#PCDATA)>
<!ELEMENT telefono (#PCDATA)>
<!ELEMENT planes (plan*)>
<!ELEMENT plan (nombre, precio, ventajas)>
<!ATTLIST plan id ID #REQUIRED>
<!ELEMENT ventajas (ventaja*)>
<!ELEMENT ventaja (#PCDATA)>

=== Josecgh/festival-tech/festival.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE festival SYSTEM 'festival.dtd'>
<festival>
  <nombre>Festival Tech 2026</nombre>
  <ciudad>Oviedo</ciudad>
  <fechas>
    <fecha>
      <dia>Viernes</dia>
      <mes>OCT</mes>
      <num>23</num>
      <anio>2026</anio>
    </fecha>
    <fecha>
      <dia>Sábado</dia>
      <mes>OCT</mes>
      <num>24</num>
      <anio>2026</anio>
    </fecha>
  </fechas>
  <lugar>Centro Joven Digital</lugar>

  <actividades>
    <actividad id="a1" tipo="robotica">
      <titulo>Batalla de Robots</titulo>
      <descripcion>Competición de robots diseñados por estudiantes.</descripcion>
      <hora>10:00</hora>
      <precio>Gratis</precio>
    </actividad>
    <actividad id="a2" tipo="videojuegos">
      <titulo>Torneo Gaming Retro</titulo>
      <descripcion>Competición de videojuegos clásicos y actuales.</descripcion>
      <hora>12:00</hora>
      <precio>3€</precio>
    </actividad>
    <actividad id="a3" tipo="ia">
      <titulo>Taller de Inteligencia Artificial</titulo>
      <descripcion>Aprende cómo funciona una IA creando un pequeño chatbot.</descripcion>
      <hora>16:00</hora>
      <precio>5€</precio>
    </actividad>
    <actividad id="a4" tipo="ciberseguridad">
      <titulo>Masterclass sobre ciberseguridad</titulo>
      <descripcion>Aprende a blindar tu empresa contra ciberataques y estafas.</descripcion>
      <hora>18:00</hora>
      <precio>Gratis</precio>
    </actividad>
  </actividades>
  <contacto>
    <email>info@festivaltech.com</email>
    <telefono>666555444</telefono>
  </contacto>
  <planes>
    <plan id="plan1">
      <nombre>General</nombre>
      <precio>25€</precio>
      <ventajas>
        <ventaja>Acceso a la convención</ventaja>
        <ventaja>Música en vivo</ventaja>
        <ventaja>Networking básico</ventaja>
      </ventajas>
    </plan>
    <plan id="plan2">
      <nombre>Pro Tech</nombre>
      <precio>55€</precio>
      <ventajas>
        <ventaja>Todo lo de General</ventaja>
        <ventaja>Acceso a charlas VIP</ventaja>
        <ventaja>Consumición + Regalo Tech</ventaja>
        <ventaja>Zona de descanso exclusiva</ventaja>
      </ventajas>
    </plan>
  </planes>
</festival>
